site_name: Technical notes
docs_dir: docs

repo_url: https://github.com/adhtruong/notes
edit_uri: edit/main/docs/

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      type: timeago
  - mermaid2

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - content.code.annotate
    - navigation.indexes

  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
